version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smart_restaurant_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/identity-db/01_init_identity.sql:/docker-entrypoint-initdb.d/01_init_identity.sql
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  mysql_data:
