using System.Globalization;
using System.Text;
using ClosedXML.Excel;
using ReservationService.DTOs;
using ReservationService.Models;

namespace ReservationService.Services;

/// <summary>
/// Helper for generating luxury executive Excel workbooks (.xlsx) and metadata-enriched CSV exports (SR-248).
/// </summary>
public static class SpreadsheetExportHelper
{
    private static readonly char[] FormulaTriggers = ['=', '+', '-', '@'];

    public static string EscapeCsvField(string? field)
    {
        if (string.IsNullOrEmpty(field))
        {
            return string.Empty;
        }

        var text = field;
        if (FormulaTriggers.Contains(text[0]))
        {
            text = "'" + text;
        }

        if (text.Contains(',') || text.Contains('"') || text.Contains('\n') || text.Contains('\r'))
        {
            return $"\"{text.Replace("\"", "\"\"")}\"";
        }

        return text;
    }

    public static byte[] BuildReservationsXlsx(
        IReadOnlyList<Reservation> reservations,
        AdminReservationQuery query,
        string? adminEmail = null)
    {
        using var workbook = new XLWorkbook();
        var ws = workbook.Worksheets.Add("Reservation Ledger");

        // 1. Title Banner
        ws.Range("A2:M2").Merge();
        var title = ws.Cell("A2");
        title.Value = "CINNAMON BISTRO — EXECUTIVE RESERVATION ROSTER";
        title.Style.Font.Bold = true;
        title.Style.Font.FontSize = 14;
        title.Style.Font.FontColor = XLColor.White;
        title.Style.Fill.BackgroundColor = XLColor.FromHtml("#1E293B");
        title.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        title.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        ws.Row(2).Height = 32;

        // 2. Sub-banner
        ws.Range("A3:M3").Merge();
        var sub = ws.Cell("A3");
        sub.Value = "OPERATIONS & GUEST SERVICES • ADMINISTRATIVE MASTER ROSTER";
        sub.Style.Font.Bold = true;
        sub.Style.Font.FontSize = 9;
        sub.Style.Font.FontColor = XLColor.White;
        sub.Style.Fill.BackgroundColor = XLColor.FromHtml("#C5A059");
        sub.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        sub.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        ws.Row(3).Height = 18;

        // 3. Metadata summary
        void StyleMetaLabel(IXLCell cell, string text)
        {
            cell.Value = text;
            cell.Style.Font.Bold = true;
            cell.Style.Font.FontSize = 9;
            cell.Style.Font.FontColor = XLColor.FromHtml("#475569");
            cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#F8FAFC");
            cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        }
        void StyleMetaValue(IXLCell cell, string text)
        {
            cell.Value = text;
            cell.Style.Font.FontSize = 9;
            cell.Style.Font.FontColor = XLColor.FromHtml("#1E293B");
            cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        }

        ws.Row(5).Height = 20;
        StyleMetaLabel(ws.Cell("B5"), "Date Window:");
        var fromStr = query.VisitFrom?.ToString("yyyy-MM-dd") ?? "Start";
        var toStr = query.VisitTo?.ToString("yyyy-MM-dd") ?? "Present";
        StyleMetaValue(ws.Cell("C5"), $"{fromStr} to {toStr}");

        StyleMetaLabel(ws.Cell("E5"), "Generated Date (UTC):");
        StyleMetaValue(ws.Cell("F5"), DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss") + " UTC");

        ws.Row(6).Height = 20;
        StyleMetaLabel(ws.Cell("B6"), "Status Filter:");
        StyleMetaValue(ws.Cell("C6"), string.IsNullOrWhiteSpace(query.Status) ? "All Statuses" : query.Status);

        StyleMetaLabel(ws.Cell("E6"), "Generated By:");
        StyleMetaValue(ws.Cell("F6"), string.IsNullOrWhiteSpace(adminEmail) ? "System Administrator" : adminEmail);

        ws.Row(7).Height = 20;
        StyleMetaLabel(ws.Cell("B7"), "Customer / Table:");
        var filterCrit = !string.IsNullOrWhiteSpace(query.Customer)
            ? $"Customer: {query.Customer}"
            : (!string.IsNullOrWhiteSpace(query.TableNumber) ? $"Table: {query.TableNumber}" : "All");
        StyleMetaValue(ws.Cell("C7"), filterCrit);

        StyleMetaLabel(ws.Cell("E7"), "Total Records:");
        var totalCell = ws.Cell("F7");
        totalCell.Value = $"{reservations.Count} Records";
        totalCell.Style.Font.Bold = true;
        totalCell.Style.Font.FontSize = 9;
        totalCell.Style.Font.FontColor = XLColor.FromHtml("#047857");
        totalCell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

        // Row 8: Spacer
        ws.Row(8).Height = 14;

        // 4. Data Headers
        var headers = new[]
        {
            "Reservation ID", "Booking Reference", "Customer ID", "Customer Name", "Customer Email",
            "Customer Phone", "Table Number", "Visit Date", "Start Time", "End Time",
            "Guest Count", "Status", "Created At (UTC)"
        };

        ws.Row(9).Height = 26;
        for (int i = 0; i < headers.Length; i++)
        {
            var cell = ws.Cell(9, i + 1);
            cell.Value = headers[i];
            cell.Style.Font.Bold = true;
            cell.Style.Font.FontSize = 9.5;
            cell.Style.Font.FontColor = XLColor.White;
            cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#1E293B");
            cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
            cell.Style.Alignment.Horizontal = (i == 0 || i == 2 || i == 6 || i == 7 || i == 8 || i == 9 || i == 10 || i == 11)
                ? XLAlignmentHorizontalValues.Center
                : XLAlignmentHorizontalValues.Left;
            cell.Style.Border.BottomBorder = XLBorderStyleValues.Medium;
            cell.Style.Border.BottomBorderColor = XLColor.FromHtml("#C5A059");
        }

        // 5. Data Rows
        for (int idx = 0; idx < reservations.Count; idx++)
        {
            var res = reservations[idx];
            var rowNum = 10 + idx;
            var row = ws.Row(rowNum);
            row.Height = 22;

            var isAlt = idx % 2 == 1;
            var rowBg = isAlt ? XLColor.FromHtml("#FAF8F4") : XLColor.White;

            ws.Cell(rowNum, 1).Value = res.Id;
            ws.Cell(rowNum, 2).Value = res.BookingReference;
            ws.Cell(rowNum, 3).Value = res.CustomerId;
            ws.Cell(rowNum, 4).Value = string.IsNullOrWhiteSpace(res.CustomerName) ? "Guest" : res.CustomerName;
            ws.Cell(rowNum, 5).Value = res.CustomerEmail;

            // Formatted Phone as explicit text
            var phoneCell = ws.Cell(rowNum, 6);
            phoneCell.SetValue(res.CustomerPhone ?? string.Empty);
            phoneCell.Style.NumberFormat.Format = "@";

            ws.Cell(rowNum, 7).Value = string.IsNullOrWhiteSpace(res.TableNumber) ? "N/A" : res.TableNumber;
            ws.Cell(rowNum, 8).Value = res.StartDateTime.ToString("yyyy-MM-dd");
            ws.Cell(rowNum, 9).Value = res.StartDateTime.ToString("HH:mm");
            ws.Cell(rowNum, 10).Value = res.EndDateTime.ToString("HH:mm");
            ws.Cell(rowNum, 11).Value = res.GuestCount;

            var statusCell = ws.Cell(rowNum, 12);
            statusCell.Value = res.Status;

            ws.Cell(rowNum, 13).Value = res.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss");

            for (int col = 1; col <= headers.Length; col++)
            {
                var c = ws.Cell(rowNum, col);
                c.Style.Font.FontSize = 9;
                c.Style.Font.FontColor = XLColor.FromHtml("#201A15");
                c.Style.Fill.BackgroundColor = rowBg;
                c.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                c.Style.Border.OutsideBorderColor = XLColor.FromHtml("#E2E8F0");
                c.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

                if (col == 1 || col == 2 || col == 3 || col == 7 || col == 8 || col == 9 || col == 10 || col == 11 || col == 13)
                {
                    c.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                }
            }

            var st = (res.Status ?? "").ToLowerInvariant();
            statusCell.Style.Font.Bold = true;
            statusCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            if (st == "confirmed")
            {
                statusCell.Style.Font.FontColor = XLColor.FromHtml("#047857");
                statusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#ECFDF5");
            }
            else if (st == "pending")
            {
                statusCell.Style.Font.FontColor = XLColor.FromHtml("#B45309");
                statusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#FFFBEB");
            }
            else if (st == "cancelled")
            {
                statusCell.Style.Font.FontColor = XLColor.FromHtml("#991B1B");
                statusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#FEF2F2");
            }
            else if (st == "completed")
            {
                statusCell.Style.Font.FontColor = XLColor.FromHtml("#1D4ED8");
                statusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#EFF6FF");
            }
        }

        ws.Columns().AdjustToContents();

        ws.Column(1).Width = Math.Max(ws.Column(1).Width, 16);
        ws.Column(2).Width = Math.Max(ws.Column(2).Width, 22);
        ws.Column(4).Width = Math.Max(ws.Column(4).Width, 24);
        ws.Column(5).Width = Math.Max(ws.Column(5).Width, 30);
        ws.Column(6).Width = Math.Max(ws.Column(6).Width, 20);
        ws.Column(8).Width = Math.Max(ws.Column(8).Width, 16);
        ws.Column(13).Width = Math.Max(ws.Column(13).Width, 22);

        using var ms = new MemoryStream();
        workbook.SaveAs(ms);
        return ms.ToArray();
    }

    public static byte[] BuildOrdersXlsx(
        IReadOnlyList<AdminOrderItemDto> orders,
        AdminOrderQueryDto query,
        string? adminEmail = null)
    {
        using var workbook = new XLWorkbook();
        var ws = workbook.Worksheets.Add("Operational Orders");

        // Title Banner
        ws.Range("A2:N2").Merge();
        var title = ws.Cell("A2");
        title.Value = "CINNAMON BISTRO — OPERATIONAL ORDERS ROSTER";
        title.Style.Font.Bold = true;
        title.Style.Font.FontSize = 14;
        title.Style.Font.FontColor = XLColor.White;
        title.Style.Fill.BackgroundColor = XLColor.FromHtml("#1E293B");
        title.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        title.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        ws.Row(2).Height = 32;

        // Sub-banner
        ws.Range("A3:N3").Merge();
        var sub = ws.Cell("A3");
        sub.Value = "FOOD & BEVERAGE SERVICE • ADMINISTRATIVE ORDERS LEDGER";
        sub.Style.Font.Bold = true;
        sub.Style.Font.FontSize = 9;
        sub.Style.Font.FontColor = XLColor.White;
        sub.Style.Fill.BackgroundColor = XLColor.FromHtml("#C5A059");
        sub.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        sub.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        ws.Row(3).Height = 18;

        void StyleMetaLabel(IXLCell cell, string text)
        {
            cell.Value = text;
            cell.Style.Font.Bold = true;
            cell.Style.Font.FontSize = 9;
            cell.Style.Font.FontColor = XLColor.FromHtml("#475569");
            cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#F8FAFC");
            cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        }
        void StyleMetaValue(IXLCell cell, string text)
        {
            cell.Value = text;
            cell.Style.Font.FontSize = 9;
            cell.Style.Font.FontColor = XLColor.FromHtml("#1E293B");
            cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        }

        ws.Row(5).Height = 20;
        StyleMetaLabel(ws.Cell("B5"), "Date Window:");
        var fromStr = query.DateFrom?.ToString("yyyy-MM-dd") ?? "Start";
        var toStr = query.DateTo?.ToString("yyyy-MM-dd") ?? "Present";
        StyleMetaValue(ws.Cell("C5"), $"{fromStr} to {toStr}");

        StyleMetaLabel(ws.Cell("E5"), "Generated Date (UTC):");
        StyleMetaValue(ws.Cell("F5"), DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss") + " UTC");

        ws.Row(6).Height = 20;
        StyleMetaLabel(ws.Cell("B6"), "Order Type / Status:");
        var typeStr = string.IsNullOrWhiteSpace(query.OrderType) ? "All Types" : query.OrderType;
        var statusStr = string.IsNullOrWhiteSpace(query.Status) ? "All Statuses" : query.Status;
        StyleMetaValue(ws.Cell("C6"), $"{typeStr} / {statusStr}");

        StyleMetaLabel(ws.Cell("E6"), "Generated By:");
        StyleMetaValue(ws.Cell("F6"), string.IsNullOrWhiteSpace(adminEmail) ? "System Administrator" : adminEmail);

        ws.Row(7).Height = 20;
        StyleMetaLabel(ws.Cell("B7"), "Customer / Reference:");
        var filterCrit = !string.IsNullOrWhiteSpace(query.Customer)
            ? $"Customer: {query.Customer}"
            : (!string.IsNullOrWhiteSpace(query.OrderReference) ? $"Ref: {query.OrderReference}" : "All");
        StyleMetaValue(ws.Cell("C7"), filterCrit);

        StyleMetaLabel(ws.Cell("E7"), "Total Orders:");
        var totalCell = ws.Cell("F7");
        totalCell.Value = $"{orders.Count} Orders";
        totalCell.Style.Font.Bold = true;
        totalCell.Style.Font.FontSize = 9;
        totalCell.Style.Font.FontColor = XLColor.FromHtml("#047857");
        totalCell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

        ws.Row(8).Height = 14;

        var headers = new[]
        {
            "Order ID", "Order Reference", "Order Type", "Table Number", "Reservation ID",
            "Customer ID", "Customer Name", "Customer Email", "Customer Phone", "Order Status",
            "Total Amount (LKR)", "Payment Status", "Payment Method", "Created At (UTC)"
        };

        ws.Row(9).Height = 26;
        for (int i = 0; i < headers.Length; i++)
        {
            var cell = ws.Cell(9, i + 1);
            cell.Value = headers[i];
            cell.Style.Font.Bold = true;
            cell.Style.Font.FontSize = 9.5;
            cell.Style.Font.FontColor = XLColor.White;
            cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#1E293B");
            cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
            cell.Style.Alignment.Horizontal = (i == 0 || i == 1 || i == 2 || i == 3 || i == 4 || i == 5 || i == 9 || i == 11 || i == 12 || i == 13)
                ? XLAlignmentHorizontalValues.Center
                : (i == 10 ? XLAlignmentHorizontalValues.Right : XLAlignmentHorizontalValues.Left);
            cell.Style.Border.BottomBorder = XLBorderStyleValues.Medium;
            cell.Style.Border.BottomBorderColor = XLColor.FromHtml("#C5A059");
        }

        for (int idx = 0; idx < orders.Count; idx++)
        {
            var ord = orders[idx];
            var rowNum = 10 + idx;
            var row = ws.Row(rowNum);
            row.Height = 22;

            var isAlt = idx % 2 == 1;
            var rowBg = isAlt ? XLColor.FromHtml("#FAF8F4") : XLColor.White;

            ws.Cell(rowNum, 1).Value = ord.OrderId;
            ws.Cell(rowNum, 2).Value = ord.OrderReference;
            ws.Cell(rowNum, 3).Value = ord.OrderType == "ReservationPreOrder" ? "Reservation Pre-order" : "Dine-in";
            ws.Cell(rowNum, 4).Value = string.IsNullOrWhiteSpace(ord.TableNumber) ? "N/A" : ord.TableNumber;
            ws.Cell(rowNum, 5).Value = ord.ReservationId.HasValue ? ord.ReservationId.Value.ToString() : "N/A";
            ws.Cell(rowNum, 6).Value = ord.CustomerId;
            ws.Cell(rowNum, 7).Value = string.IsNullOrWhiteSpace(ord.CustomerName) ? "Guest" : ord.CustomerName;
            ws.Cell(rowNum, 8).Value = ord.CustomerEmail;

            var phoneCell = ws.Cell(rowNum, 9);
            phoneCell.SetValue(ord.CustomerPhone ?? string.Empty);
            phoneCell.Style.NumberFormat.Format = "@";

            var statusCell = ws.Cell(rowNum, 10);
            statusCell.Value = ord.Status;

            var amountCell = ws.Cell(rowNum, 11);
            amountCell.Value = ord.TotalAmount;
            amountCell.Style.NumberFormat.Format = "#,##0.00";

            var payStatusCell = ws.Cell(rowNum, 12);
            payStatusCell.Value = ord.PaymentStatus;

            ws.Cell(rowNum, 13).Value = string.IsNullOrWhiteSpace(ord.PaymentMethod) ? "N/A" : ord.PaymentMethod;
            ws.Cell(rowNum, 14).Value = ord.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss");

            for (int col = 1; col <= headers.Length; col++)
            {
                var c = ws.Cell(rowNum, col);
                c.Style.Font.FontSize = 9;
                c.Style.Font.FontColor = XLColor.FromHtml("#201A15");
                c.Style.Fill.BackgroundColor = rowBg;
                c.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                c.Style.Border.OutsideBorderColor = XLColor.FromHtml("#E2E8F0");
                c.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

                if (col == 1 || col == 2 || col == 3 || col == 4 || col == 5 || col == 6 || col == 10 || col == 12 || col == 13 || col == 14)
                {
                    c.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                }
                else if (col == 11)
                {
                    c.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
                }
            }

            var st = (ord.Status ?? "").ToLowerInvariant();
            statusCell.Style.Font.Bold = true;
            statusCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            if (st == "served" || st == "completed")
            {
                statusCell.Style.Font.FontColor = XLColor.FromHtml("#047857");
                statusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#ECFDF5");
            }
            else if (st == "pending" || st == "preparing")
            {
                statusCell.Style.Font.FontColor = XLColor.FromHtml("#B45309");
                statusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#FFFBEB");
            }
            else if (st == "cancelled")
            {
                statusCell.Style.Font.FontColor = XLColor.FromHtml("#991B1B");
                statusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#FEF2F2");
            }
            else if (st == "ready")
            {
                statusCell.Style.Font.FontColor = XLColor.FromHtml("#1D4ED8");
                statusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#EFF6FF");
            }

            var pst = (ord.PaymentStatus ?? "").ToLowerInvariant();
            payStatusCell.Style.Font.Bold = true;
            payStatusCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            if (pst == "paid" || pst == "success")
            {
                payStatusCell.Style.Font.FontColor = XLColor.FromHtml("#047857");
                payStatusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#ECFDF5");
            }
            else
            {
                payStatusCell.Style.Font.FontColor = XLColor.FromHtml("#B45309");
                payStatusCell.Style.Fill.BackgroundColor = XLColor.FromHtml("#FFFBEB");
            }
        }

        ws.Columns().AdjustToContents();

        ws.Column(1).Width = Math.Max(ws.Column(1).Width, 14);
        ws.Column(2).Width = Math.Max(ws.Column(2).Width, 20);
        ws.Column(7).Width = Math.Max(ws.Column(7).Width, 24);
        ws.Column(8).Width = Math.Max(ws.Column(8).Width, 30);
        ws.Column(9).Width = Math.Max(ws.Column(9).Width, 20);
        ws.Column(11).Width = Math.Max(ws.Column(11).Width, 20);
        ws.Column(14).Width = Math.Max(ws.Column(14).Width, 22);

        using var ms = new MemoryStream();
        workbook.SaveAs(ms);
        return ms.ToArray();
    }

    public static byte[] BuildReservationsCsvWithMetadata(
        IReadOnlyList<Reservation> reservations,
        AdminReservationQuery query,
        string? adminEmail = null)
    {
        var builder = new StringBuilder();

        // 1. Data Table Headers (Strict RFC 4180 - uniform 13 columns across all records)
        var headers = new[]
        {
            "Reservation ID", "Booking Reference", "Customer ID", "Customer Name", "Customer Email",
            "Customer Phone", "Table Number", "Visit Date", "Start Time", "End Time",
            "Guest Count", "Status", "Created At (UTC)"
        };
        builder.AppendLine(string.Join(",", headers.Select(EscapeCsvField)));

        // 3. Rows
        foreach (var res in reservations)
        {
            var row = new[]
            {
                res.Id.ToString(CultureInfo.InvariantCulture),
                res.BookingReference,
                res.CustomerId.ToString(CultureInfo.InvariantCulture),
                string.IsNullOrWhiteSpace(res.CustomerName) ? "Guest" : res.CustomerName,
                res.CustomerEmail,
                // Prefix phone with tab in CSV so Excel interprets it as Text without scientific notation
                "\t" + (res.CustomerPhone ?? string.Empty),
                string.IsNullOrWhiteSpace(res.TableNumber) ? "N/A" : res.TableNumber,
                res.StartDateTime.ToString("yyyy-MM-dd"),
                res.StartDateTime.ToString("HH:mm"),
                res.EndDateTime.ToString("HH:mm"),
                res.GuestCount.ToString(CultureInfo.InvariantCulture),
                res.Status,
                res.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")
            };
            builder.AppendLine(string.Join(",", row.Select(EscapeCsvField)));
        }

        return EncodeUtf8Bom(builder.ToString());
    }

    public static byte[] BuildOrdersCsvWithMetadata(
        IReadOnlyList<AdminOrderItemDto> orders,
        AdminOrderQueryDto query,
        string? adminEmail = null)
    {
        var builder = new StringBuilder();

        // 1. Data Table Headers (Strict RFC 4180 - uniform 14 columns across all records)
        var headers = new[]
        {
            "Order ID", "Order Reference", "Order Type", "Table Number", "Reservation ID",
            "Customer ID", "Customer Name", "Customer Email", "Customer Phone", "Order Status",
            "Total Amount (LKR)", "Payment Status", "Payment Method", "Created At (UTC)"
        };
        builder.AppendLine(string.Join(",", headers.Select(EscapeCsvField)));

        // 3. Rows
        foreach (var ord in orders)
        {
            var row = new[]
            {
                ord.OrderId.ToString(CultureInfo.InvariantCulture),
                ord.OrderReference,
                ord.OrderType == "ReservationPreOrder" ? "Reservation Pre-order" : "Dine-in",
                string.IsNullOrWhiteSpace(ord.TableNumber) ? "N/A" : ord.TableNumber,
                ord.ReservationId.HasValue ? ord.ReservationId.Value.ToString(CultureInfo.InvariantCulture) : "N/A",
                ord.CustomerId.ToString(CultureInfo.InvariantCulture),
                string.IsNullOrWhiteSpace(ord.CustomerName) ? "Guest" : ord.CustomerName,
                ord.CustomerEmail,
                "\t" + (ord.CustomerPhone ?? string.Empty),
                ord.Status,
                ord.TotalAmount.ToString("F2", CultureInfo.InvariantCulture),
                ord.PaymentStatus,
                string.IsNullOrWhiteSpace(ord.PaymentMethod) ? "N/A" : ord.PaymentMethod,
                ord.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")
            };
            builder.AppendLine(string.Join(",", row.Select(EscapeCsvField)));
        }

        return EncodeUtf8Bom(builder.ToString());
    }

    private static byte[] EncodeUtf8Bom(string content)
    {
        var encoding = new UTF8Encoding(true);
        var preamble = encoding.GetPreamble();
        var body = encoding.GetBytes(content);

        var result = new byte[preamble.Length + body.Length];
        Buffer.BlockCopy(preamble, 0, result, 0, preamble.Length);
        Buffer.BlockCopy(body, 0, result, preamble.Length, body.Length);
        return result;
    }
}
