import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getAdminReservations, updateAdminReservationStatus } from '../../services/tableService';
import { formatReservationDateTime, statusClassName } from '../availability/reservationHistoryView';

const initialFilters = { visitFrom: '', visitTo: '', status: '', tableNumber: '', bookingReference: '', page: 1, pageSize: 20 };
export default function AdminReservationsPage() {
  const [filters, setFilters] = useState(initialFilters); const [data, setData] = useState(null); const [error, setError] = useState(''); const [pending, setPending] = useState(null);
  const load = async (next = filters) => { setData(null); setError(''); try { setData(await getAdminReservations(next)); } catch (e) { setError(e?.response?.status === 403 ? 'You are not authorised to manage reservations.' : 'Unable to load reservations. Please try again.'); } };
  useEffect(() => { load(filters); }, [filters.page]);
  const submit = (event) => { event.preventDefault(); setFilters({ ...filters, page: 1 }); load({ ...filters, page: 1 }); };
  const changeStatus = async (item, status) => { if (!window.confirm(`Change ${item.bookingReference} to ${status}?`)) return; setPending(item.reservationId); try { await updateAdminReservationStatus(item.reservationId, status); await load(); } catch (e) { setError(e?.response?.data?.message || 'The status could not be changed. Refresh and try again.'); } finally { setPending(null); } };
  return <main className="availability-page"><div className="availability-content"><Link className="link-jelly-back" to="/admin">← Back to dashboard</Link><header className="availability-header"><p className="active-tables-eyebrow">Operations</p><h1>Reservation management</h1><p>Filter daily bookings and apply only permitted lifecycle actions.</p></header>
    <form className="availability-form admin-reservation-filters" onSubmit={submit}><div className="availability-fields"><label>From<input type="date" value={filters.visitFrom} onChange={e => setFilters({ ...filters, visitFrom: e.target.value })} /></label><label>To<input type="date" value={filters.visitTo} onChange={e => setFilters({ ...filters, visitTo: e.target.value })} /></label><label>Status<select value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value })}><option value="">All</option>{['Pending','Confirmed','Cancelled','Completed'].map(s => <option key={s}>{s}</option>)}</select></label><label>Table<input value={filters.tableNumber} onChange={e => setFilters({ ...filters, tableNumber: e.target.value })} /></label><label>Reference<input value={filters.bookingReference} onChange={e => setFilters({ ...filters, bookingReference: e.target.value })} /></label></div><button className="btn-jelly-primary" type="submit">Apply filters</button><button className="btn-jelly-secondary" type="button" onClick={() => { setFilters(initialFilters); load(initialFilters); }}>Clear</button></form>
    {error && <div className="availability-state active-tables-error" role="alert">{error}</div>}{!data && !error && <div className="availability-state" role="status">Loading reservations…</div>}
    {data?.items?.length === 0 && <div className="availability-state">No reservations match these filters.</div>}{data?.items?.length > 0 && <div className="admin-reservation-list">{data.items.map(item => <article key={item.reservationId} className="reservation-history-card"><div className="reservation-history-card-header"><div><p className="reservation-reference">{item.bookingReference}</p><h2>Table {item.tableNumber}</h2><small>Customer #{item.customerId}</small></div><span className={statusClassName(item.status)}>{item.status}</span></div><p>{formatReservationDateTime(item.startDateTime)} - {formatReservationDateTime(item.endDateTime)} · {item.guestCount} guests</p>{['Pending','Confirmed'].includes(item.status) && <div className="admin-reservation-actions">{item.status === 'Pending' && <button disabled={pending === item.reservationId} onClick={() => changeStatus(item, 'Confirmed')}>Confirm</button>}<button disabled={pending === item.reservationId} onClick={() => changeStatus(item, 'Cancelled')}>Cancel</button>{item.status === 'Confirmed' && <button disabled={pending === item.reservationId} onClick={() => changeStatus(item, 'Completed')}>Complete</button>}</div>}</article>)}</div>}
    {data?.totalPages > 1 && <nav className="reservation-pagination"><button className="btn-jelly-secondary" disabled={filters.page === 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>Previous</button><span>Page {data.page} of {data.totalPages}</span><button className="btn-jelly-secondary" disabled={filters.page >= data.totalPages} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Next</button></nav>}</div></main>;
}
